builders_admin/urls.py
from django.urls import path
from .views import (
    login_view, home_view, banner_home,  about_as_home, why_us, main_services, specialized_in, projects, testimonials, 
    about_view, banner_about, company_profile, 
    services_overview, services_banner, post_banner_content, detailed_service, 
    news_overview, news_banner, post_news_banner_content, detailed_news, contact_overview,
    contact_overview, contact_banner, contact_info
    )

from django.contrib.auth.decorators import login_required

app_name = "builders_admin"

urlpatterns = [
    path('', login_view, name='login_view'),
    path('home/', login_required(home_view), name='home_view'),
    path('home/banner/', login_required(banner_home), name='banner_home'),
    path('home/about-us/', login_required(about_as_home), name='about_as_home'),
    path('home/why_us/', login_required(why_us), name='why_us'),
    path('home/main-services/', login_required(main_services), name='main_services'),
    path('home/specialized-in/', login_required(specialized_in), name='specialized_in'),
    path('home/recent-projects/', login_required(projects), name='recent_projects'),
    path('home/testimonials/', login_required(testimonials), name='testimonials'),


    path('about-us/', login_required(about_view), name='about_view'),
    path('about-us/banner', login_required(banner_about), name='banner_about'),
    path('about-us/company-profile', login_required(company_profile), name='company_profile'),

    path('services/', login_required(services_overview), name='services_overview'),
    path('services/banner/', login_required(services_banner), name='services_banner'),
    path('services/post-banner-content/', login_required(post_banner_content), name='post_banner_content'),
    path('services/post-banner-content/<slug:service_id>', login_required(detailed_service), name='detailed_service'),

    path('news/', login_required(news_overview), name='news_overview'),
    path('news/banner/', login_required(news_banner), name='news_banner'),
    path('news/post-banner', login_required(post_news_banner_content), name='post_news_banner_content'),
    path('news/post-banner/<slug:news_id>', login_required(detailed_news), name='detailed_news'),

    path('contact-us/', login_required(contact_overview), name='contact_overview'),
    path('contact-us/banner/', login_required(contact_banner), name='contact_banner'),
    path('contact-us/info/', login_required(contact_info), name='contact_info'),
]

classic_builders_inc/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admins/', admin.site.urls),
    path('admin/', include("builders_admin.urls")),
    # path('tinymce/', include('tinymce.urls')),
    path('', include("home.urls")),
    path('about-us/', include("about_us.urls")),
    path('services/', include("services.urls")),
    path('news/', include("news.urls")),
    path('contact-us/', include("contact_us.urls")),
]

home/urls.py
from django.urls import path
from .views import home


app_name = "home"

urlpatterns = [
    path('', home, name='home')
]

news/urls.py
from django.urls import path
from .views import news, detailed_news


app_name = "news"

urlpatterns = [
    path('', news, name='news'),
    path('<slug:news_id>/', detailed_news, name='detailed_news')
]

builders_admin/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

news/models.py
from django.db import models
import os
import re
import uuid

# Create your models here.


class Banner(models.Model):
    image = models.ImageField(upload_to='static/uploads/news/banners', blank=True)
    heading = models.CharField(max_length=150, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk and Banner.objects.exists():
            raise ValidationError('There can be only one Banner instance')
        
        return super(Banner, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banner'


    def __str__(self):
        return self.heading

    @property
    def alt_image(self):
        filename = os.path.basename(self.image.name)
        return (re.sub(r'[\W_]+', ' ', os.path.splitext(filename)[0]).replace(" ", "-").lower())
    

class News(models.Model):
    news_id = models.UUIDField(primary_key=True, default=str(uuid.uuid4), editable=False)
    thumbnail = models.ImageField(upload_to='static/uploads/news/thumbnails', blank=True)
    short_heading = models.CharField(max_length=50, blank=True)
    short_description = models.CharField(max_length=300, blank=True)
    info_button_text = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='static/uploads/news', blank=True)
    heading = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateField(auto_now_add=True)

    @property
    def alt_thumbnail(self):
        filename = os.path.basename(self.thumbnail.name)
        return re.sub(r'[\W_]+', ' ', os.path.splitext(filename)[0]).replace(" ", "-").lower()

    @property
    def alt_image(self):
        filename = os.path.basename(self.image.name)
        return re.sub(r'[\W_]+', ' ', os.path.splitext(filename)[0]).replace(" ", "-").lower()

    def __str__(self):
        return self.short_heading

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'

builders_admin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from home.models import Banner, AboutUs, AboutServices, WhyUs, MainServices, SpecializedIn, SpecializedInServices, ProjectSectionTitle, Projects, TestimonialSection, Testimonial
from about_us.models import Banner as about_us_banner, CompanyProfile
from services.models import Banner as serv_banner, PostBannerContent, Services
from news.models import Banner as nw_banner, News
from contact_us.models import Banner as ct_banner, ContactInfo
import uuid
from django.contrib.auth.decorators import login_required



# Create your views here.

def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('builders_admin:home_view')
        else:
            return render(request, 'builders_admin/login.html', {'error_message': True})

    return render(request, 'builders_admin/login.html')


def home_view(request):
    data = {
        "banners": Banner.objects.all(),
        "about_us": AboutUs.objects.first(),
        "about_services": AboutServices.objects.all(),
        'why_us': WhyUs.objects.first(),
        'main_services': MainServices.objects.first(),
        "specialized_in": SpecializedIn.objects.first(),
        'specialized_in_services': SpecializedInServices.objects.all(),
        "project_section_title": ProjectSectionTitle.objects.first(),
        'projects': Projects.objects.all(),
        "testimonial_section": TestimonialSection.objects.first(),
        "testimonials": Testimonial.objects.all(),
        'current_view': 'home',
        'current_sub_view': 'home'
    }
    return render(request, 'builders_admin/home/home.html', context=data)


def banner_home(request):
    if request.method == 'POST':
        action = request.POST.get('action')

        banner_id = request.POST.get("object-id")
        heading = request.POST.get("heading")
        sub_heading = request.POST.get("sub-heading")
        description = request.POST.get("banner-description")
        button_text = request.POST.get("read-more")
        image = request.FILES.get("image")

        if action == 'update':
            try:
                banner = Banner.objects.get(id=banner_id)
                banner.heading = heading
                banner.sub_heading = sub_heading
                banner.description = description
                banner.button_text = button_text
                if image:
                    banner.image = image

                banner.save()

            except Exception as e:
                print(e)

        elif action == 'delete':
            total_banners = Banner.objects.count()
            
            if total_banners >= 2:
                try:
                    banner = Banner.objects.get(id=banner_id)
                    banner.delete()

                except Exception as e:
                    print(e)

            else:
                pass

        elif action == 'add':
            last_banner = Banner.objects.order_by('-id').first()
            
            new_banner = Banner(
                image=last_banner.image,
                heading=last_banner.heading,
                sub_heading=last_banner.sub_heading,
                description=last_banner.description,
                button_text=last_banner.button_text
            )
            new_banner.save()

    data = {
        "banners": Banner.objects.all(),
        'current_view': 'home',
        'current_sub_view': 'banner'
    }

    return render(request, 'builders_admin/home/banner.html', context=data)


def about_as_home(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        
        if action == 'save-about-us':
            try:
                about_us_instance = AboutUs.objects.first()

                heading = request.POST.get("heading")
                sub_heading = request.POST.get("sub-heading")
                description = request.POST.get("banner-description")

                about_us_instance.heading = heading
                about_us_instance.sub_heading = sub_heading
                about_us_instance.description = description
                about_us_instance.save()
            
            except Exception as e:
                print(e)

        elif action == 'update':
            try:
                object_id = request.POST.get('object-id')
                service_name = request.POST.get('service-name')
                service_image = request.FILES.get("service-image")
                service_icon = request.FILES.get("service-icon")

                about_us_service = AboutServices.objects.get(id=object_id)

                about_us_service.service_name = service_name
                if service_image:
                    about_us_service.service_image = service_image
                
                if service_icon:
                    about_us_service.service_icon = service_icon
                
                about_us_service.save()

            except Exception as e:
                print(e)

        elif action == 'add':
            try:
                last_service = AboutServices.objects.order_by('-id').first()

                new_service = AboutServices(
                    service_name=last_service.service_name,
                    service_image=last_service.service_image,
                    service_icon=last_service.service_icon,
                )

                new_service.save()
            
            except Exception as e:
                print(e)

        elif action == 'delete':
            object_id = request.POST.get('object-id')
            total_services = AboutServices.objects.count()
            
            if total_services >= 2:
                try:
                    service = AboutServices.objects.get(id=object_id)
                    service.delete()

                except Exception as e:
                    print(e)

            else:
                pass

        
    data = {
        'about_us_instance': AboutUs.objects.first(),
        'about_us_services': AboutServices.objects.all(),
        'current_view': 'home',
        'current_sub_view': 'about-us'
    }
    return render(request, 'builders_admin/home/about-us.html', context=data)



def why_us(request):
    if request.method == 'POST':

        action = request.POST.get('action')
        
        if action == 'update':

            try:
                why_us_instance = WhyUs.objects.first()

                heading = request.POST.get("heading")
                sub_heading = request.POST.get("sub-heading")
                description = request.POST.get("description")
                image = request.FILES.get("image")
                image_text = request.POST.get("image-text")
                mission_heading = request.POST.get("mission-heading")
                mission_text = request.POST.get("mission-text")
                vision_heading = request.POST.get("vision-heading")
                vision_text = request.POST.get("vision-text")

                why_us_instance.heading = heading
                why_us_instance.sub_heading = sub_heading
                why_us_instance.description = description
                why_us_instance.image_text = image_text
                why_us_instance.mission_heading = mission_heading
                why_us_instance.mission_text = mission_text
                why_us_instance.vision_heading = vision_heading
                why_us_instance.vision_text = vision_text
            
                if image:
                    why_us_instance.image = image


                why_us_instance.save()

            except Exception as e:
                print(e)


    data = {
        "why_us": WhyUs.objects.first(),
        'current_view': 'home',
        'current_sub_view': 'why-us'

    }

    return render(request, 'builders_admin/home/why-us.html', context=data)


def main_services(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        
        if action == 'update':
            try:
                main_services_instance = MainServices.objects.first()

                heading = request.POST.get("heading")
                sub_heading = request.POST.get("sub-heading")
                description = request.POST.get("description")
                service_1_title = request.POST.get("service_1_title")
                service_1_image = request.FILES.get("service-image-1")
                service_2_title = request.POST.get("service_2_title")
                service_2_image = request.FILES.get("service-image-2")
                service_3_title = request.POST.get("service_3_title")
                service_3_image = request.FILES.get("service-image-3")
                button_text = request.POST.get("button_text")

                main_services_instance.heading = heading
                main_services_instance.sub_heading = sub_heading
                main_services_instance.description = description
                main_services_instance.service_1_title = service_1_title
                main_services_instance.service_2_title = service_2_title
                main_services_instance.service_3_title = service_3_title
                main_services_instance.button_text = button_text

                if service_1_image:
                    main_services_instance.service_1_image = service_1_image
                if service_2_image:
                    main_services_instance.service_2_image = service_2_image
                if service_3_image:
                    main_services_instance.service_3_image = service_3_image

                main_services_instance.save()


            except Exception as e:
                print(e)

    data = {
        'main_services': MainServices.objects.first(),

news/views.py
from django.shortcuts import render
from news.models import Banner, News
from contact_us.models import ContactInfo


# Create your views here.

def news(request):
    data = {
        "banner": Banner.objects.first(),
        "all_news": News.objects.all(),
        "contact_data": ContactInfo.objects.first(),
    }

    return render(request, 'news/news.html', context=data)


def detailed_news(request, news_id):
    data = {
        "news": News.objects.get(news_id=news_id),
        "contact_data": ContactInfo.objects.first(),
    }

    return render(request, 'news/detailed-news.html', context=data)

builders_admin/templates/builders_admin/news/banner.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | Classic Builders INC</title>
    <link rel="stylesheet" href="{% static "/css/admin-styling/tw.css" %}">
    <link rel="stylesheet" href="{% static "css/admin-styling/style.css" %}">
    <link rel="shortcut icon" href="https://showcaseonline.store/classic-builders-inc/logo-2.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="bg-[#272f40]">
    <main class="flex flex-col-reverse lg:flex-row max-w-maincontent m-auto bg-white">
        {% include "builders_admin/navbar.html" %}
        <aside class="p-6">
            <section>
                <div class="sm:mb-8 flex items-center justify-between">
                    <h1 class="font-semibold text-[1.4rem] sm:font-normal sm:text-3xl text-nowrap">News Banner</h1>
                </div>

                <form class="mt-10 w-full item" action="{% url "builders_admin:news_banner" %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="w-full image-container">
                        <img class="display-image select-none cursor-pointer hover:contrast-[1.15] transition ease-in delay-100" src="{{ banner.image.url }}" alt="{{ banner.alt_image }}" draggable="false">
                        <input type="file" accept="image/*" class="hidden" name="image">
                    </div>
                    <div class="flex flex-row gap-2 items-center justify-around my-2 w-full">
                        <input type="text" class="w-full text-sm font-normal px-2 py-2 border-none outline-none rounded-md bg-blue-50 sm:py-3" placeholder="{{ banner.heading }}" value="{{ banner.heading }}" name="heading">
                    </div>
                    <div>
                        <button type="submit" name="action" value="update" class="bg-blue-500 px-2 py-2 text-center rounded-md w-full text-base outline-none text-white transition ease-in delay-100 focus:bg-green-500" title="Update and Save">Save</button>
                    </div>
                </form>
            </section>
        </aside>
    </main>

    <script src="{% static "js/admin-scripts/nav-sub-menu.js" %}"></script>
    <script type="module" src="{% static "js/admin-scripts/item-management.mjs" %}"></script>
</body>
</html>

builders_admin/templates/builders_admin/news/news-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | Classic Builders INC</title>
    <link rel="stylesheet" href="{% static "/css/admin-styling/tw.css" %}">
    <link rel="stylesheet" href="{% static "css/admin-styling/style.css" %}">
    <link rel="shortcut icon" href="https://showcaseonline.store/classic-builders-inc/logo-2.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static "css/admin-styling/tinymce-resets.css" %}">
    <script src="{% static "js/tinymce/js/tinymce/tinymce.min.js" %}"></script>
</head>
<body class="bg-[#272f40]">
    <main class="flex flex-col-reverse lg:flex-row max-w-maincontent m-auto bg-white">
        {% include "builders_admin/navbar.html" %}
        <aside class="p-6">
            <form action="{% url "builders_admin:detailed_news" news.news_id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <section>
                    <div class="sm:mb-8 flex items-center justify-between">
                        <h1 class="font-semibold text-[1.4rem] sm:font-normal sm:text-3xl text-nowrap">{{ news.short_heading }}</h1>
                    </div>
    
                    <div class="item">
                        <div class="w-full image-container">
                            <img class="display-image select-none cursor-pointer hover:contrast-[1.15] transition ease-in delay-100" src="{{ news.image.url }}" alt="{{ news.alt_image }}" draggable="false">
                            <input type="file" accept="image/*" class="hidden" name="image">
                        </div>
                    </div>
    
                    <div class="flex flex-row gap-2 items-center justify-around my-2 w-full">
                        <input type="text" class="w-full text-sm font-normal px-2 py-2 border-none outline-none rounded-md bg-blue-50 sm:py-3" placeholder="{{ news.heading }}" value="{{ news.heading }}" name="heading">
                    </div>
    
                    <div>
                        <textarea id="detailed-news-editor" name="description">
                            {{ news.description|safe }}
                        </textarea>
                    </div>

                    <div class="mt-4">
                        <button type="submit" name="action" value="update-news-details" class="bg-blue-500 px-2 py-2 text-center rounded-md w-full text-base outline-none text-white transition ease-in delay-100 focus:bg-green-500" title="Update and Save">Save</button>
                    </div>
                </section>
            </form>
        </aside>
    </main>
    <script src="{% static "js/admin-scripts/nav-sub-menu.js" %}"></script>
    <script type="module" src="{% static "js/admin-scripts/item-management.mjs" %}"></script>
    <script src="{% static "js/admin-scripts/tinymce-settings.js" %}"></script>
</body>
</html>

builders_admin/templates/builders_admin/news/post-banner.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | Classic Builders INC</title>
    <link rel="stylesheet" href="{% static "/css/admin-styling/tw.css" %}">
    <link rel="stylesheet" href="{% static "css/admin-styling/style.css" %}">
    <link rel="shortcut icon" href="https://showcaseonline.store/classic-builders-inc/logo-2.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="bg-[#272f40]">
    <main class="flex flex-col-reverse lg:flex-row max-w-maincontent m-auto bg-white">
        {% include "builders_admin/navbar.html" %}
        <aside class="p-6">
            <section class="mt-14">
                <div class="sm:mb-8 flex items-center justify-between">
                    <h1 class="font-semibold text-[1.4rem] sm:font-normal sm:text-3xl text-nowrap">All News</h1>
                </div>

                <div class="mt-10 flex gap-2 flex-wrap justify-start items-center">
                    <!-- Max row size set to 3 items per view | If total items are 3 then add 'xxl:max-w-[32.9%]' in eash item container -->
                     {% for news in all_news %}
                     {% if news %}
                     <!-- Item Starts Here -->
                     <form class="item border border-gray-300 rounded-sm px-2 py-3 max-w-[509px] midsm:flex midsm:flex-col midsm:flex-shrink mid:smflex-grow midsm:max-w-[49%] xxxl:max-w-[32.7%]" action="{% url "builders_admin:post_news_banner_content" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="text" class="hidden" name="object-id" value="{{ news.news_id }}">
                        <div class="relative image-container">
                                <img class="display-image select-none cursor-pointer hover:contrast-[1.15] transition ease-in delay-100" src="{{ news.thumbnail.url }}" alt="{{ news.alt_thumbnail }}" draggable="false">
                                {% if all_news|length >= 2 %}
                                <button type="submit" name="action" value="remove-news-card">
                                    <i title="Remove News" class="fa-solid fa-xmark absolute text-red-500 bg-white transition ease-in px-3 py-[0.6rem] rounded-full top-3 right-3 cursor-pointer active:bg-black active:text-white active:scale-75" tabindex="0"></i>
                                </button>
                                {% endif %}
                                <input type="file" accept="image/*" class="hidden" name="thumbnail">
                            </div>
                            <div class="flex flex-col gap-2 items-center justify-around my-2">
                                <input type="text" class="w-full text-sm font-normal px-2 py-2 border-none outline-none rounded-md bg-blue-50 sm:py-3" placeholder="Heading" value="{{ news.short_heading }}" name="short_heading">
                                <textarea class="w-full min-h-24 max-h-24 text-sm font-normal px-2 py-2 border-none outline-none rounded-md bg-blue-50 sm:py-3-50" placeholder="Short Description" name="short_description">{{ news.short_description }}</textarea>
                                <input type="text" class="bg-primary px-2 py-2 text-center rounded-md w-full text-base outline-none placeholder:text-black placeholder:text-center text-black transition ease-in delay-100 focus:bg-blue-50" placeholder="Read More" name="info_button_text" value="{{ news.info_button_text }}">
                            </div>
                            <div class="flex justify-between gap-2">
                                <button type="submit" name="action" value="update-news-card" class="bg-blue-500 px-2 py-2 text-center rounded-md w-full text-base outline-none text-white transition ease-in delay-100 focus:bg-green-500" title="Update and Save">Save</button>
                                <a href="{% url "builders_admin:detailed_news" news.news_id %}" class="bg-orange-500 px-2 py-2 text-center rounded-md w-full text-base outline-none text-white transition ease-in delay-100 focus:bg-green-500">Detailed View</a>
                            </div>
                        </form>
                        <!-- Item Ends Here -->
                     {% endif %}
                     {% endfor %}
                    </div>
                    <form action="{% url "builders_admin:post_news_banner_content" %}" method="post" class="text-center">
                        {% csrf_token %}
                        <button class="text-[1.4rem] sm:text-3xl lg:mr-6 cursor-pointer mt-12" name="action" value="add-more-news" type="submit">
                            <i class="fa-solid fa-plug-circle-plus text-green-500 transition ease-in hover:text-green-600 active:text-green-200 active:scale-75" title="Add More Slides" tabindex="0"></i>
                        </button>
                    </form>
            </section>
        </aside>
    </main>
    <script src="{% static "js/admin-scripts/nav-sub-menu.js" %}"></script>
    <script type="module" src="{% static "js/admin-scripts/item-management.mjs" %}"></script>
</body>
</html>