classic_builders_inc/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admins/', admin.site.urls),
    path('admin/', include("builders_admin.urls")),
    # path('tinymce/', include('tinymce.urls')),
    path('', include("home.urls")),
    path('about-us/', include("about_us.urls")),
    path('services/', include("services.urls")),
    path('news/', include("news.urls")),
    path('contact-us/', include("contact_us.urls")),
]

home/urls.py
from django.urls import path
from .views import home


app_name = "home"

urlpatterns = [
    path('', home, name='home')
]

news/urls.py
from django.urls import path
from .views import news, detailed_news


app_name = "news"

urlpatterns = [
    path('', news, name='news'),
    path('<slug:news_id>/', detailed_news, name='detailed_news')
]

news/models.py
from django.db import models
import os
import re
import uuid

# Create your models here.


class Banner(models.Model):
    image = models.ImageField(upload_to='static/uploads/news/banners', blank=True)
    heading = models.CharField(max_length=150, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk and Banner.objects.exists():
            raise ValidationError('There can be only one Banner instance')
        
        return super(Banner, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banner'


    def __str__(self):
        return self.heading

    @property
    def alt_image(self):
        filename = os.path.basename(self.image.name)
        return (re.sub(r'[\W_]+', ' ', os.path.splitext(filename)[0]).replace(" ", "-").lower())
    

class News(models.Model):
    news_id = models.UUIDField(primary_key=True, default=str(uuid.uuid4), editable=False)
    thumbnail = models.ImageField(upload_to='static/uploads/news/thumbnails', blank=True)
    short_heading = models.CharField(max_length=50, blank=True)
    short_description = models.CharField(max_length=300, blank=True)
    info_button_text = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='static/uploads/news', blank=True)
    heading = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateField(auto_now_add=True)

    @property
    def alt_thumbnail(self):
        filename = os.path.basename(self.thumbnail.name)
        return re.sub(r'[\W_]+', ' ', os.path.splitext(filename)[0]).replace(" ", "-").lower()

    @property
    def alt_image(self):
        filename = os.path.basename(self.image.name)
        return re.sub(r'[\W_]+', ' ', os.path.splitext(filename)[0]).replace(" ", "-").lower()

    def __str__(self):
        return self.short_heading

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'

news/views.py
from django.shortcuts import render
from news.models import Banner, News
from contact_us.models import ContactInfo


# Create your views here.

def news(request):
    data = {
        "banner": Banner.objects.first(),
        "all_news": News.objects.all(),
        "contact_data": ContactInfo.objects.first(),
    }

    return render(request, 'news/news.html', context=data)


def detailed_news(request, news_id):
    data = {
        "news": News.objects.get(news_id=news_id),
        "contact_data": ContactInfo.objects.first(),
    }

    return render(request, 'news/detailed-news.html', context=data)

news/templates/news/detailed-news.html
{% load static %}
<!DOCTYPE html>
<html
  data-wf-page="64ddb2f80e56ffe6218ca2f0"
  data-wf-site="649a95c241c0447e7e6ce0d5"
  lang="en"
>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Classic Builders Inc. provides news and analysis for general contracting projects. We cover news, focusing on topics of home construction, bathroom renovation…"
    />
    <meta name="keywords" content="News" />
    <title>Read Our Latest News & Insights | Classic Builders Inc</title>
    <link
      href="{% static 'images/fav-2.png' %}"
      rel="shortcut icon"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/webflow.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
  </head>
  <body>
    <!-- Navbar Section Starts Here -->
    {% include "navigator/navbar.html" %}
    <!-- Navbar Section Ends Here -->

    <!-- Header Section Ends Here -->
    <!-- Hero Section Starts Here -->
    <section>
        <div class="mt-1 mb-3 container-one m-auto">
          <img class="select-none" src="{{ news.image.url }}" alt="{{ news.alt_image }}" draggable="false">
        </div>
      </section>
      <!-- Hero Section Ends Here -->
      <!-- Blog Title Section Starts Here -->
      <section class="container-one m-auto mb-10 px-4 lg:px-0">
        <h1 class="font-bold text-xl sm:text-2xl lg:3xl">{{ news.heading }}</h1>
        <div class="flex items-center gap-3 text-sm mt-2 mb-16">
          <a href="###" class="text-xs sm:text-sm text-[#1c2436] font-medium underline ease-in duration-300">Leave a comment</a>
          <p class="text-xs sm:text-sm text-black font-medium ease-in duration-300">{{ news.created_at }}</p>
        </div>
        <div class="flex flex-col gap-6">
          {{ news.description|safe }}
        </div>
      </section>
      <!-- Blog Title Section Ends Here -->
      <!-- Footer Section Starts Here -->

    <!-- Footer Section Starts Here -->
    {% include "footer/footer.html" %}
    <!-- Footer Section Ends Here -->

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/webflow.js' %}"></script>
    <script src="{% static 'js/swiper.js' %}"></script>
    <script src="{% static 'js/swiper-settings.js' %}"></script>
  </body>
</html>

news/templates/news/news.html
{% load static %}
<!DOCTYPE html>
<html
  data-wf-page="64ddb2f80e56ffe6218ca2f0"
  data-wf-site="649a95c241c0447e7e6ce0d5"
  lang="en"
>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Classic Builders Inc. provides news and analysis for general contracting projects. We cover news, focusing on topics of home construction, bathroom renovation…"
    />
    <meta name="keywords" content="News" />
    <title>Read Our Latest News & Insights | Classic Builders Inc</title>
    <link
      href="{% static 'images/fav-2.png' %}"
      rel="shortcut icon"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/webflow.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
  </head>
  <body>
    <!-- Navbar Section Starts Here -->
    {% include "navigator/navbar.html" %}
    <!-- Navbar Section Ends Here -->

    <!-- Hero Section Starts Here -->
    <section>
      <div class="relative flex justify-start items-center mt-1 mb-16">
        <img
          class="w-[100vw] h-[45vh] select-none brightness-90 contrast-50 object-cover"
          src="{{ banner.image.url }}"
          alt="{{ banner.alt_image }}"
          draggable="false"
        />
        <div class="w-[100vw] absolute">
          <h1
            class="text-white text-3xl font-semibold px-11 sm:text-5xl container-one m-auto lg:px-0"
          >
            {{ banner.heading }}
          </h1>
        </div>
      </div>
    </section>
    <!-- Hero Section Ends Here -->

    <!-- Blogs  Section Starts Here -->
    <section class="my-20">
      <div
        class="container-one m-auto flex flex-col items-center justify-center gap-4 sm:flex-row sm:flex-wrap ease-in duration-300"
      >
      {% for news in all_news %}
      {% if news %}
      <!-- News Item Starts Here -->
      <a href="{% url "news:detailed_news" news.news_id %}" class="ease-in duration-300">
        <div
          style="border: 1px solid #80808030"
          class="max-w-[400px] flex flex-col gap-2 text-black ease-in duration-300 rounded-md group"
        >
          <div class="relative flex justify-center items-center">
            <img
              class="w-full select-none brightness-75 group-hover:brightness-[0.4] ease-in duration-300 rounded-t-md"
              src="{{ news.thumbnail.url }}"
              alt="{{ news.alt_thumbnail}}"
              draggable="false"
            />
            <i
              class="fas fa-long-arrow-alt-right text-white absolute opacity-0 ease-in duration-300 group-hover:opacity-100"
              aria-hidden="true"
            ></i>
            <p
              class="absolute top-4 right-4 text-black font-semibold text-xs group-hover:opacity-0"
            >
            {{ news.created_at }}
          </p>
          </div>
          <div class="px-6">
            <h4 class="font-semibold text-[1.05rem] leading-7">
              {{ news.short_heading }}
            </h4>
          </div>
          <div class="flex flex-col gap-4 px-6 pb-8">
            <p class="text-base leading-6 text-black">
              {{ news.short_description }}
            </p>
            <p
              class="text-base leading-6 text-[#f6b61b] hover:underline ease-in duration-300"
            >
            {{ news.info_button_text }}
            </p>
          </div>
        </div>
      </a>
      <!-- News Item Ends Here -->
      {% endif %}
      {% endfor %}
      </div>
    </section>
    <!-- Blogs  Section Ends Here -->

    <!-- Footer Section Starts Here -->
    {% include "footer/footer.html" %}
    <!-- Footer Section Ends Here -->

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/webflow.js' %}"></script>
    <script src="{% static 'js/swiper.js' %}"></script>
    <script src="{% static 'js/swiper-settings.js' %}"></script>
  </body>
</html>