builders_admin/urls.py
from django.urls import path
from .views import (
    login_view, home_view, banner_home,  about_as_home, why_us, main_services, specialized_in, projects, testimonials, 
    about_view, banner_about, company_profile, 
    services_overview, services_banner, post_banner_content, detailed_service, 
    news_overview, news_banner, post_news_banner_content, detailed_news, contact_overview,
    contact_overview, contact_banner, contact_info
    )

from django.contrib.auth.decorators import login_required

app_name = "builders_admin"

urlpatterns = [
    path('', login_view, name='login_view'),
    path('home/', login_required(home_view), name='home_view'),
    path('home/banner/', login_required(banner_home), name='banner_home'),
    path('home/about-us/', login_required(about_as_home), name='about_as_home'),
    path('home/why_us/', login_required(why_us), name='why_us'),
    path('home/main-services/', login_required(main_services), name='main_services'),
    path('home/specialized-in/', login_required(specialized_in), name='specialized_in'),
    path('home/recent-projects/', login_required(projects), name='recent_projects'),
    path('home/testimonials/', login_required(testimonials), name='testimonials'),


    path('about-us/', login_required(about_view), name='about_view'),
    path('about-us/banner', login_required(banner_about), name='banner_about'),
    path('about-us/company-profile', login_required(company_profile), name='company_profile'),

    path('services/', login_required(services_overview), name='services_overview'),
    path('services/banner/', login_required(services_banner), name='services_banner'),
    path('services/post-banner-content/', login_required(post_banner_content), name='post_banner_content'),
    path('services/post-banner-content/<slug:service_id>', login_required(detailed_service), name='detailed_service'),

    path('news/', login_required(news_overview), name='news_overview'),
    path('news/banner/', login_required(news_banner), name='news_banner'),
    path('news/post-banner', login_required(post_news_banner_content), name='post_news_banner_content'),
    path('news/post-banner/<slug:news_id>', login_required(detailed_news), name='detailed_news'),

    path('contact-us/', login_required(contact_overview), name='contact_overview'),
    path('contact-us/banner/', login_required(contact_banner), name='contact_banner'),
    path('contact-us/info/', login_required(contact_info), name='contact_info'),
]

classic_builders_inc/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admins/', admin.site.urls),
    path('admin/', include("builders_admin.urls")),
    # path('tinymce/', include('tinymce.urls')),
    path('', include("home.urls")),
    path('about-us/', include("about_us.urls")),
    path('services/', include("services.urls")),
    path('news/', include("news.urls")),
    path('contact-us/', include("contact_us.urls")),
]

home/urls.py
from django.urls import path
from .views import home


app_name = "home"

urlpatterns = [
    path('', home, name='home')
]

builders_admin/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

builders_admin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from home.models import Banner, AboutUs, AboutServices, WhyUs, MainServices, SpecializedIn, SpecializedInServices, ProjectSectionTitle, Projects, TestimonialSection, Testimonial
from about_us.models import Banner as about_us_banner, CompanyProfile
from services.models import Banner as serv_banner, PostBannerContent, Services
from news.models import Banner as nw_banner, News
from contact_us.models import Banner as ct_banner, ContactInfo
import uuid
from django.contrib.auth.decorators import login_required



# Create your views here.

def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('builders_admin:home_view')
        else:
            return render(request, 'builders_admin/login.html', {'error_message': True})

    return render(request, 'builders_admin/login.html')


def home_view(request):
    data = {
        "banners": Banner.objects.all(),
        "about_us": AboutUs.objects.first(),
        "about_services": AboutServices.objects.all(),
        'why_us': WhyUs.objects.first(),
        'main_services': MainServices.objects.first(),
        "specialized_in": SpecializedIn.objects.first(),
        'specialized_in_services': SpecializedInServices.objects.all(),
        "project_section_title": ProjectSectionTitle.objects.first(),
        'projects': Projects.objects.all(),
        "testimonial_section": TestimonialSection.objects.first(),
        "testimonials": Testimonial.objects.all(),
        'current_view': 'home',
        'current_sub_view': 'home'
    }
    return render(request, 'builders_admin/home/home.html', context=data)


def banner_home(request):
    if request.method == 'POST':
        action = request.POST.get('action')

        banner_id = request.POST.get("object-id")
        heading = request.POST.get("heading")
        sub_heading = request.POST.get("sub-heading")
        description = request.POST.get("banner-description")
        button_text = request.POST.get("read-more")
        image = request.FILES.get("image")

        if action == 'update':
            try:
                banner = Banner.objects.get(id=banner_id)
                banner.heading = heading
                banner.sub_heading = sub_heading
                banner.description = description
                banner.button_text = button_text
                if image:
                    banner.image = image

                banner.save()

            except Exception as e:
                print(e)

        elif action == 'delete':
            total_banners = Banner.objects.count()
            
            if total_banners >= 2:
                try:
                    banner = Banner.objects.get(id=banner_id)
                    banner.delete()

                except Exception as e:
                    print(e)

            else:
                pass

        elif action == 'add':
            last_banner = Banner.objects.order_by('-id').first()
            
            new_banner = Banner(
                image=last_banner.image,
                heading=last_banner.heading,
                sub_heading=last_banner.sub_heading,
                description=last_banner.description,
                button_text=last_banner.button_text
            )
            new_banner.save()

    data = {
        "banners": Banner.objects.all(),
        'current_view': 'home',
        'current_sub_view': 'banner'
    }

    return render(request, 'builders_admin/home/banner.html', context=data)


def about_as_home(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        
        if action == 'save-about-us':
            try:
                about_us_instance = AboutUs.objects.first()

                heading = request.POST.get("heading")
                sub_heading = request.POST.get("sub-heading")
                description = request.POST.get("banner-description")

                about_us_instance.heading = heading
                about_us_instance.sub_heading = sub_heading
                about_us_instance.description = description
                about_us_instance.save()
            
            except Exception as e:
                print(e)

        elif action == 'update':
            try:
                object_id = request.POST.get('object-id')
                service_name = request.POST.get('service-name')
                service_image = request.FILES.get("service-image")
                service_icon = request.FILES.get("service-icon")

                about_us_service = AboutServices.objects.get(id=object_id)

                about_us_service.service_name = service_name
                if service_image:
                    about_us_service.service_image = service_image
                
                if service_icon:
                    about_us_service.service_icon = service_icon
                
                about_us_service.save()

            except Exception as e:
                print(e)

        elif action == 'add':
            try:
                last_service = AboutServices.objects.order_by('-id').first()

                new_service = AboutServices(
                    service_name=last_service.service_name,
                    service_image=last_service.service_image,
                    service_icon=last_service.service_icon,
                )

                new_service.save()
            
            except Exception as e:
                print(e)

        elif action == 'delete':
            object_id = request.POST.get('object-id')
            total_services = AboutServices.objects.count()
            
            if total_services >= 2:
                try:
                    service = AboutServices.objects.get(id=object_id)
                    service.delete()

                except Exception as e:
                    print(e)

            else:
                pass

        
    data = {
        'about_us_instance': AboutUs.objects.first(),
        'about_us_services': AboutServices.objects.all(),
        'current_view': 'home',
        'current_sub_view': 'about-us'
    }
    return render(request, 'builders_admin/home/about-us.html', context=data)



def why_us(request):
    if request.method == 'POST':

        action = request.POST.get('action')
        
        if action == 'update':

            try:
                why_us_instance = WhyUs.objects.first()

                heading = request.POST.get("heading")
                sub_heading = request.POST.get("sub-heading")
                description = request.POST.get("description")
                image = request.FILES.get("image")
                image_text = request.POST.get("image-text")
                mission_heading = request.POST.get("mission-heading")
                mission_text = request.POST.get("mission-text")
                vision_heading = request.POST.get("vision-heading")
                vision_text = request.POST.get("vision-text")

                why_us_instance.heading = heading
                why_us_instance.sub_heading = sub_heading
                why_us_instance.description = description
                why_us_instance.image_text = image_text
                why_us_instance.mission_heading = mission_heading
                why_us_instance.mission_text = mission_text
                why_us_instance.vision_heading = vision_heading
                why_us_instance.vision_text = vision_text
            
                if image:
                    why_us_instance.image = image


                why_us_instance.save()

            except Exception as e:
                print(e)


    data = {
        "why_us": WhyUs.objects.first(),
        'current_view': 'home',
        'current_sub_view': 'why-us'

    }

    return render(request, 'builders_admin/home/why-us.html', context=data)


def main_services(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        
        if action == 'update':
            try:
                main_services_instance = MainServices.objects.first()

                heading = request.POST.get("heading")
                sub_heading = request.POST.get("sub-heading")
                description = request.POST.get("description")
                service_1_title = request.POST.get("service_1_title")
                service_1_image = request.FILES.get("service-image-1")
                service_2_title = request.POST.get("service_2_title")
                service_2_image = request.FILES.get("service-image-2")
                service_3_title = request.POST.get("service_3_title")
                service_3_image = request.FILES.get("service-image-3")
                button_text = request.POST.get("button_text")

                main_services_instance.heading = heading
                main_services_instance.sub_heading = sub_heading
                main_services_instance.description = description
                main_services_instance.service_1_title = service_1_title
                main_services_instance.service_2_title = service_2_title
                main_services_instance.service_3_title = service_3_title
                main_services_instance.button_text = button_text

                if service_1_image:
                    main_services_instance.service_1_image = service_1_image
                if service_2_image:
                    main_services_instance.service_2_image = service_2_image
                if service_3_image:
                    main_services_instance.service_3_image = service_3_image

                main_services_instance.save()


            except Exception as e:
                print(e)

    data = {
        'main_services': MainServices.objects.first(),

builders_admin/templates/builders_admin/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | Classic Builders INC</title>
    <link rel="stylesheet" href="{% static "css/admin-styling/tw.css" %}">
    <link rel="stylesheet" href="{% static "css/admin-styling/style.css" %}">
    <link rel="shortcut icon" href="https://showcaseonline.store/classic-builders-inc/logo-2.png" type="image/x-icon">
</head>
<body class="bg-secondary">
    <main class="flex justify-around items-center max-w-[1200px] m-auto h-[100vh] sm:h-fit">
        <aside class="">
            <img class="h-[100vh] select-none object-cover hidden sm:block" src="https://showcaseonline.store/classic-builders-inc/649a95c241c0447e7e6ce0d5/services/inner/Residential.jpg" alt="residential" draggable="false">
        </aside>

        <main
          class="w-[380px] px-6 py-7 rounded-md flex flex-col items-center mx-8 bg-white h-[550px] translate-x-0 sm:-translate-x-36"
          style="border: 1px solid #80808030"
        >
          <form action="###" method="post" class="">
            {% csrf_token %}
            <div class="mt-14 mb-3 flex flex-col items-center gap-2">
                <img class="w-12" src="https://showcaseonline.store/classic-builders-inc/logo-2.png" alt="site logo">
                <h1 class="text-[1.4rem] sm:mb-8 sm:text-3xl text-nowrap">Classic Builders INC</h1>
            </div>

            {% if error_message %}
            <div class="">
              <p class="mb-4 text-red-500 text-sm">Invalid Email or Password</p>
            </div>
            {% endif %}

            <div class="mb-4">
              <label class="text-sm font-medium" for="email">Email</label>
              <input
                class="w-full text-sm font-normal px-2 py-2 border-none outline-none rounded-md bg-blue-50 sm:py-3"
                placeholder="williams.alexander@nowheremail.com"
                type="email"
                id="email"
                name="email"
                required
              />
            </div>
            <div class="mb-4">
              <label class="text-sm font-medium" for="email">Password</label>
              <input
                class="w-full text-sm font-normal px-2 py-2 border-none outline-none rounded-md bg-blue-50 sm:py-3"
                placeholder="******************"
                type="password"
                id="password"
                name="password"
                required
              />
            </div>
            <div class="mt-12">
              <button
                class="bg-primary text-black py-2 px-12 rounded-md w-full text-base"
                type="submit"
              >
                Submit
              </button>
            </div>
          </form>
        </main>
    </main>
</body>
</html>

builders_admin/templates/builders_admin/navbar.html
{% load static %}
<header class="bg-secondary h-fit fixed left-0 right-0 bottom-0 lg:-translate-x-1 lg:h-[100vh] lg:min-w-56 lg:sticky lg:top-0 z-50 overflow-y-auto overflow-x-hidden">
    <!-- Site Logo Here -->
    <a href="###" class="hidden lg:block">
        <img class="w-44 px-8 py-6" src="https://showcaseonline.store/classic-builders-inc/logo-2-w.png" alt="site-logo">
    </a>

    <!-- Navbar Starts Here -->
    <ul class="lg:mt-8 flex justify-start items-center xsm:justify-center lg:flex-col lg:items-start lg:gap-8 overflow-x-scroll lg:overflow-hidden">
        
        
        <div class="nav-item relative">
            <button class="transition ease-in delay-100 group">
                <li class="text-xl lg:text-base flex items-center gap-3 mx-1 py-3 px-8 rounded-sm transition ease-in delay-100 hover:bg-white group {% if current_view == 'home' %}active-nav{% endif %}">
                    <i class="fa-solid fa-house text-white group-hover:text-secondary transition ease-in delay-100"></i>
                    <p class="text-white text-sm font-semibold group-hover:text-secondary transition ease-in delay-100 hidden lg:block">Home</p>
                    <i class="fa-solid fa-chevron-down text-white text-sm"></i>
                </li>
            </button>

            <ul class=" overflow-hidden transition ease-in delay-300 rounded-t-md fixed bottom-[5.9%] bg-primary lg:static lg:bg-transparent my-2 h-0 sub-menu">
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:home_view" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'home' %}text-white lg:text-primary{% endif %}">Home</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:banner_home" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'banner' %}text-white lg:text-primary{% endif %}">Banner</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:about_as_home" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'about-us' %}text-white lg:text-primary{% endif %}">About Us</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:why_us" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'why-us' %}text-white lg:text-primary{% endif %}">Why Us</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:main_services" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'main_services' %}text-white lg:text-primary{% endif %}">Main Services</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:specialized_in" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'specialized_in' %}text-white lg:text-primary{% endif %}">Specialized In</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:recent_projects" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'projects' %}text-white lg:text-primary{% endif %}">Recent Projects</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:testimonials" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'testimonials' %}text-white lg:text-primary{% endif %}">Testimonials</a>
                </li>
            </ul>
        </div>
        <div class="nav-item relative">
            <button class="transition ease-in delay-100 group">
                
                <li class="text-xl lg:text-base flex items-center gap-3 mx-1 py-3 px-8 rounded-sm transition ease-in delay-100 hover:bg-white group {% if current_view == 'about-us' %}active-nav{% endif %}">
                    <i class="fa-solid fa-circle-info text-white group-hover:text-secondary transition ease-in delay-100"></i>
                    <p class="text-white text-sm font-semibold group-hover:text-secondary transition ease-in delay-100 hidden lg:block">About Us</p>
                    <i class="fa-solid fa-chevron-down text-white text-sm"></i>
                </li>
            </button>

            <ul class=" overflow-hidden transition ease-in delay-300 rounded-t-md fixed bottom-[5.9%] bg-primary lg:static lg:bg-transparent my-2 h-0 sub-menu">
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:about_view" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'about-us-2' %}text-white lg:text-primary{% endif %}">About Us</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:banner_about" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'banner-about' %}text-white lg:text-primary{% endif %}">Banner</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:company_profile" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'company-profile' %}text-white lg:text-primary{% endif %}">Company Profile</a>
                </li>
            </ul>
        </div>
        <div class="nav-item relative">
            <button class="transition ease-in delay-100 group">
                <li class="text-xl lg:text-base flex items-center gap-3 mx-1 py-3 px-8 rounded-sm transition ease-in delay-100 hover:bg-white group {% if current_view == 'services-overview' %}active-nav{% endif %}">
                    <i class="fa-solid fa-building text-white group-hover:text-secondary transition ease-in delay-100"></i>
                    <p class="text-white text-sm font-semibold group-hover:text-secondary transition ease-in delay-100 hidden lg:block">Services</p>
                    <i class="fa-solid fa-chevron-down text-white text-sm"></i>
                </li>
            </button>

            <ul class=" overflow-hidden transition ease-in delay-300 rounded-t-md fixed bottom-[5.9%] bg-primary lg:static lg:bg-transparent my-2 h-0 sub-menu">
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:services_overview" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'services-overview' %}text-white lg:text-primary{% endif %}">Services</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:services_banner" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'services_banner' %}text-white lg:text-primary{% endif %}">Banner</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:post_banner_content" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'post_banner_content' %}text-white lg:text-primary{% endif %}">Post Banner</a>
                </li>
            </ul>
        </div>
        <div class="nav-item relative">
            <button class="transition ease-in delay-100 group">
                <li class="text-xl lg:text-base flex items-center gap-3 mx-1 py-3 px-8 rounded-sm transition ease-in delay-100 hover:bg-white group {% if current_view == 'news-overview' %}active-nav{% endif %}">
                    <i class="fa-regular fa-newspaper text-white group-hover:text-secondary transition ease-in delay-100"></i>
                    <p class="text-white text-sm font-semibold group-hover:text-secondary transition ease-in delay-100 hidden lg:block">News</p>
                    <i class="fa-solid fa-chevron-down text-white text-sm"></i>
                </li>
            </button>

            <ul class=" overflow-hidden transition ease-in delay-300 rounded-t-md fixed bottom-[5.9%] bg-primary lg:static lg:bg-transparent my-2 h-0 sub-menu">
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:news_overview" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'news-overview' %}text-white lg:text-primary{% endif %}">News</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:news_banner" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'news_banner' %}text-white lg:text-primary{% endif %}">Banner</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:post_news_banner_content" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'post_news_banner_content' %}text-white lg:text-primary{% endif %}">Post Banner</a>
                </li>
            </ul>
        </div>
        <div class="nav-item relative">
            <button class="transition ease-in delay-100 group">
                <li class="text-xl lg:text-base flex items-center gap-3 mx-1 py-3 px-8 rounded-sm transition ease-in delay-100 hover:bg-white group {% if current_view == 'contact-overview' %}active-nav{% endif %}">
                    <i class="fa-solid fa-phone text-white group-hover:text-secondary transition ease-in delay-100"></i>
                    <p class="text-white text-sm font-semibold group-hover:text-secondary transition ease-in delay-100 hidden lg:block">Contact Us</p>
                    <i class="fa-solid fa-chevron-down text-white text-sm"></i>
                </li>
            </button>

            <ul class=" overflow-hidden transition ease-in delay-300 rounded-t-md fixed bottom-[5.9%] bg-primary lg:static lg:bg-transparent my-2 h-0 sub-menu">
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:contact_overview" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'contact-overview' %}text-white lg:text-primary{% endif %}">Contact Us</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:contact_banner" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'contact_banner' %}text-white lg:text-primary{% endif %}">Banner</a>
                </li>
                <li class="font-semibold text-secondary hover:text-white hover:font-semibold transition ease-in delay-100 mx-1 py-3 px-8 lg:text-white lg:hover:text-primary">
                    <a href="{% url "builders_admin:contact_info" %}" class="text-xs font-semibold lg:text-sm {% if current_sub_view == 'contact_info' %}text-white lg:text-primary{% endif %}">Info</a>
                </li>
            </ul>
        </div>
    </ul>
    <!-- Navbar Ends Here -->
</header>